### ISSUE TITLE
Error Is Not Allowing The Tronic247 Material To Run

### ISSUE THREAD

**Issue by sancho1952007** [Tronic247/material#144]
## I Am Getting Uncaught Type Error And Script Not Working...

material.min.js:10 Uncaught TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at Object.init (material.min.js:10:29494)
    at material.min.js:10:30107
    at material.min.js:10:116544
    at material.min.js:10:116550
    at material.min.js:10:193
    at material.min.js:10:197

**Comment by Posandu** [comment]
Can you provide some code? This seems to be an issue with your code.

**Comment by Posandu** [comment]
Closing this because no activity, feel free to reopen!
